### ISSUE TITLE
Integration of java.util.Date and python datetime

### ISSUE THREAD

**Issue by Thrameos** [Thrameos/jpype#18]
In order to facilitate plotting of data, we need to wrap java.util.Date so that numpy can use java.util.Date directly.  This will need to bit flexible as the datetime is immutable and java.util.Date is not.   No sure if this is possible.  Will need to hide all deprecated members and hide setTime() so that it meets the python contract need for dict.   The only downside to this someone may return a Date with the intent to set it.   Will likely document the issue.

**Comment by seilhan3** [comment]
Intended use for plotting
`[datetime.datetime.fromtimestamp(ts.getTime()/1000.0) for ts in  javaObject.getTimestamps()]`
