### ISSUE TITLE
Getting started?

### ISSUE THREAD

**Issue by ejfried** [Thrameos/jpype#51]
Hi,
I'm a Java guy and only a casual Python (and pyjnius) user. I saw @Thrameos's issue on the  pyjnius project and am interested in comparing the two myself, but I'm having a hard time getting started. Is there a document for Python newbs that explains how to set up JPype that I'm missing?

**Comment by Thrameos** [comment]
I would recommend starting with the [quickstart guide](https://jpype.readthedocs.io/en/latest/quickguide.html) which gives you everything you need to be dangerous in translating from Java to Python.   Then there is a [installation guide](https://jpype.readthedocs.io/en/latest/install.html) to show how to install.   Pretty much should be "pip install JPype1" on most systems, though we still need to get the 1.0.1 release pushed.  Worst cast pull the recent release wheel for your system and call "pip install JPype1-{arch}.whl" to put it on your system.   You may then need to deal with the issues of getting the JVM started which can range from dirt easy to horrible.  The worst being people with horribly broken Java installs that refuse to find the libraries (though we have another guide for that).   There is the [users guide](https://jpype.readthedocs.io/en/latest/userguide.html) and the [API reference](https://jpype.readthedocs.io/en/latest/api.html) which cover the details on using it.  And if you are in for absolute punishment you can glace at [developer guide](https://jpype.readthedocs.io/en/latest/develguide.html) which gives a glorious tour through the sausage factory down to how to track down and debug problems between layers.   

As I said to the maintainer "I think I set the record for the most documentation per user, though it helps that the divisor is very small."

**Comment by Thrameos** [comment]
Did that resolve the issue?

**Comment by ejfried** [comment]
Yes, the quckstart guide was very helpful, thanks. Will try to contribute a patch for some typos there.

**Comment by Thrameos** [comment]
Thanks.  Please make any corrections to quickstart.py which is used to build the quickstart.rst file.   If you see anything unclear or needing addition instruction please feel free to ask.   I had my son go through and proof read the guides, but they can always use some more work.   Ey cundn't spel, effin ef mi lef deepent un et.   Dyslexics untie!
